### ISSUE TITLE
3 card fill is broken.

### ISSUE THREAD

**Issue by ethanjgoldberg** [chenosaurus/poker-evaluator#4]
3CardConverter.fillHand is currently broken. It incorrectly assigns ranks to cards, and it does not look for Ace-low straights.

To see this bug in action, try
    fillHand(['as', '4s', '5d']);
or
    evalHand(['as', '4s', '5d']);

**Comment by liuming3** [comment]
you are right.
PokerEvaluator.evalHand([ 'Ah', '2s', '3c' ])
is invalid card..

**Comment by liuming3** [comment]
[ 'As', '2c', 'Kc' ]));
[ 'Ad', '2d', 'Kc' ])); they are same  output value:
