### ISSUE TITLE
evalHand causing memory leak/crash

### ISSUE THREAD

**Issue by joshdura** [chenosaurus/poker-evaluator#9]
When using `evalHand` to get the handRank, after about 3 or 4 calls, I will get the following crash/error:

```
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
15 May 11:06:42 - [nodemon] app crashed - waiting for file changes before starting...
```

I put together the following sample to help debug this:

```
var evaluator = require('poker-evaluator');

var player1 = [ '6s', '3s', 'as', '4c', '7s', '9s', '7h' ];
var player2 = [ '10s', '7d', 'as', '4c', '7s', '9s', '7h' ];
var player3 = [ 'qc', '8c', 'as', '4c', '7s', '9s', '7h' ];
var player4 = [ '9h', '4h', 'as', '4c', '7s', '9s', '7h' ];

console.log(evaluator.evalHand(player1));
console.log(evaluator.evalHand(player2));
console.log(evaluator.evalHand(player3));
console.log(evaluator.evalHand(player4));
```

This will usually log 1 or 2 successful objects, but usually not the full set.

When I run the sample, I am able to run the entire thing successfully, so I don't think this is an issue with the computer being able to handle the call.

Please let me know if you need anymore info, or if there is anything I can do to improve upon the sample.

**Comment by bartreijmer** [comment]
Ah man! I feel so stupid, I too was using `10` instead of `T`. Thanks for posting the fix, It really helped me out.
